project   = 'cellxgene-harvester-nf'
copyright = '2026, NIH-NLM'
author    = 'NIH-NLM'
release   = '1.0.0'

extensions = [
    'myst_parser',
]

# ---------------------------------------------------------------------------
# Nextflow module docs — auto-generated by docs/parse_nf_docs.py
#
# The generated files in docs/source/nextflow/ are committed so that
# GitHub Pages can build without running the script. Regenerate locally
# after any .nf change:
#
#   python3 docs/parse_nf_docs.py
#   make -C docs html
# ---------------------------------------------------------------------------

# Accepted source suffixes — .rst and .md (via myst_parser)
source_suffix = {
    '.rst': 'restructuredtext',
    '.md':  'markdown',
}

templates_path   = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

html_theme       = 'sphinx_rtd_theme'
html_static_path = ['_static']
